### ISSUE TITLE
problem running _fit_template in example script 

### ISSUE THREAD

**Issue by nnitzan** [ahwillia/affinewarp#12]
Hi 

I'm trying to run the multi_warp example code but get an error during the model fitting stage
TypeError: _fit_template() takes exactly 3 arguments (2 given) 
Any idea what went wrong? 
thanks in advance,

Noam

**Comment by ahwillia** [comment]
Thanks, that `multiwarp` functionality is a bit experimental, so I must have changed something. This commit fixed it for me: https://github.com/ahwillia/affinewarp/commit/6e26f5967330479a2698ba4c7ec8ffe2dfc276a3

Let me know if the problem persists, and check out this [working draft](https://www.biorxiv.org/content/10.1101/2020.03.02.974014v1) that I have on the topic of multi-shift time warping.
