### ISSUE TITLE
Issue downloading affinewarp due to sklearn

### ISSUE THREAD

**Issue by harshidapancholi** [ahwillia/affinewarp#22]
Hi there,
I'm unable to properly download affinewarp, which is a dependency I need, due to the deprecation of sklearn - https://github.com/scikit-learn/sklearn-pypi-package.

Is there a workaround for this?

Thanks!

**Comment by ahwillia** [comment]
I just replaced `sklearn` -> `scikit-learn` in the `requirements.txt` file. Let me know if that fixes the issue.

**Comment by harshidapancholi** [comment]
It did! Thank you so much.
